/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecruitmentManagementSystemApi);
  }
}(this, function(expect, RecruitmentManagementSystemApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RecruitmentManagementSystemApi.PlanResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlanResponse', function() {
    it('should create an instance of PlanResponse', function() {
      // uncomment below and update the code to test PlanResponse
      //var instance = new RecruitmentManagementSystemApi.PlanResponse();
      //expect(instance).to.be.a(RecruitmentManagementSystemApi.PlanResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new RecruitmentManagementSystemApi.PlanResponse();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new RecruitmentManagementSystemApi.PlanResponse();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instance = new RecruitmentManagementSystemApi.PlanResponse();
      //expect(instance).to.be();
    });

    it('should have the property jobDescription (base name: "jobDescription")', function() {
      // uncomment below and update the code to test the property jobDescription
      //var instance = new RecruitmentManagementSystemApi.PlanResponse();
      //expect(instance).to.be();
    });

    it('should have the property requiredCPA (base name: "requiredCPA")', function() {
      // uncomment below and update the code to test the property requiredCPA
      //var instance = new RecruitmentManagementSystemApi.PlanResponse();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new RecruitmentManagementSystemApi.PlanResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new RecruitmentManagementSystemApi.PlanResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new RecruitmentManagementSystemApi.PlanResponse();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new RecruitmentManagementSystemApi.PlanResponse();
      //expect(instance).to.be();
    });

  });

}));
