components:
  parameters:
    Page:
      name: page
      in: query
      description: The page number to retrieve in the paginated results.
      schema:
        type: integer
        default: 1
        minimum: 1
      required: false
      example: 2

    Limit:
      name: limit
      in: query
      description: The maximum number of items to return per page.
      schema:
        type: integer
        default: 10
        minimum: 1
        maximum: 100
      required: false
      example: 25

    SortBy:
      name: sortBy
      in: query
      description: The field used to sort the results. Supported fields depend on the endpoint (e.g., 'createdAt', 'fullName', 'status').
      schema:
        type: string
      required: false
      example: createdAt

    SortOrder:
      name: sortOrder
      in: query
      description: The order of sorting (ascending or descending).
      schema:
        type: string
        enum: [asc, desc]
      required: false
      example: desc

    SearchKeyword:
      name: keyword
      in: query
      description: A general search term to filter resources across common fields (e.g., name, email, title).
      schema:
        type: string
        minLength: 3
      required: false
      example: "Thương"

    UserRoleFilter:
      name: role
      in: query
      description: Filter users by their assigned role.
      schema:
        type: string
        enum: [ADMIN, RECRUITER, RECTOR]
      required: false
      example: RECRUITER

    RequestId:
      name: X-Request-ID
      in: header
      description: Unique identifier for the request, generated by the client, useful for tracing and debugging.
      schema:
        type: string
        format: uuid
      required: false
      example: "a1b2c3d4-e5f6-7890-abcd-ef0123456789"
