/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthResponse from './model/AuthResponse';
import ErrorDetail from './model/ErrorDetail';
import ErrorResponse from './model/ErrorResponse';
import ForgotPassword200Response from './model/ForgotPassword200Response';
import ForgotPasswordRequest from './model/ForgotPasswordRequest';
import GetAllPlans200Response from './model/GetAllPlans200Response';
import LoginRequest from './model/LoginRequest';
import PlanCreateRequest from './model/PlanCreateRequest';
import PlanResponse from './model/PlanResponse';
import RefreshToken200Response from './model/RefreshToken200Response';
import RefreshTokenRequest from './model/RefreshTokenRequest';
import ResetPasswordRequest from './model/ResetPasswordRequest';
import UpdatePlanStatusRequest from './model/UpdatePlanStatusRequest';
import User from './model/User';
import UserAdminUpdateRequest from './model/UserAdminUpdateRequest';
import UserBasicInfo from './model/UserBasicInfo';
import UserCreateRequest from './model/UserCreateRequest';
import UserSelfUpdateRequest from './model/UserSelfUpdateRequest';
import AuthApi from './api/AuthApi';
import PlansApi from './api/PlansApi';
import UsersApi from './api/UsersApi';


/**
* API for managing recruitment processes..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RecruitmentManagementSystemApi = require('index'); // See note below*.
* var xxxSvc = new RecruitmentManagementSystemApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RecruitmentManagementSystemApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RecruitmentManagementSystemApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RecruitmentManagementSystemApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthResponse model constructor.
     * @property {module:model/AuthResponse}
     */
    AuthResponse,

    /**
     * The ErrorDetail model constructor.
     * @property {module:model/ErrorDetail}
     */
    ErrorDetail,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The ForgotPassword200Response model constructor.
     * @property {module:model/ForgotPassword200Response}
     */
    ForgotPassword200Response,

    /**
     * The ForgotPasswordRequest model constructor.
     * @property {module:model/ForgotPasswordRequest}
     */
    ForgotPasswordRequest,

    /**
     * The GetAllPlans200Response model constructor.
     * @property {module:model/GetAllPlans200Response}
     */
    GetAllPlans200Response,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The PlanCreateRequest model constructor.
     * @property {module:model/PlanCreateRequest}
     */
    PlanCreateRequest,

    /**
     * The PlanResponse model constructor.
     * @property {module:model/PlanResponse}
     */
    PlanResponse,

    /**
     * The RefreshToken200Response model constructor.
     * @property {module:model/RefreshToken200Response}
     */
    RefreshToken200Response,

    /**
     * The RefreshTokenRequest model constructor.
     * @property {module:model/RefreshTokenRequest}
     */
    RefreshTokenRequest,

    /**
     * The ResetPasswordRequest model constructor.
     * @property {module:model/ResetPasswordRequest}
     */
    ResetPasswordRequest,

    /**
     * The UpdatePlanStatusRequest model constructor.
     * @property {module:model/UpdatePlanStatusRequest}
     */
    UpdatePlanStatusRequest,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserAdminUpdateRequest model constructor.
     * @property {module:model/UserAdminUpdateRequest}
     */
    UserAdminUpdateRequest,

    /**
     * The UserBasicInfo model constructor.
     * @property {module:model/UserBasicInfo}
     */
    UserBasicInfo,

    /**
     * The UserCreateRequest model constructor.
     * @property {module:model/UserCreateRequest}
     */
    UserCreateRequest,

    /**
     * The UserSelfUpdateRequest model constructor.
     * @property {module:model/UserSelfUpdateRequest}
     */
    UserSelfUpdateRequest,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The PlansApi service constructor.
    * @property {module:api/PlansApi}
    */
    PlansApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
