/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecruitmentManagementSystemApi);
  }
}(this, function(expect, RecruitmentManagementSystemApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RecruitmentManagementSystemApi.PlansApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlansApi', function() {
    describe('createRecruitmentPlan', function() {
      it('should call createRecruitmentPlan successfully', function(done) {
        //uncomment below and update the code to test createRecruitmentPlan
        //instance.createRecruitmentPlan(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllPlans', function() {
      it('should call getAllPlans successfully', function(done) {
        //uncomment below and update the code to test getAllPlans
        //instance.getAllPlans(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlanById', function() {
      it('should call getPlanById successfully', function(done) {
        //uncomment below and update the code to test getPlanById
        //instance.getPlanById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePlanStatus', function() {
      it('should call updatePlanStatus successfully', function(done) {
        //uncomment below and update the code to test updatePlanStatus
        //instance.updatePlanStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
