/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserBasicInfo from './UserBasicInfo';

/**
 * The AuthResponse model module.
 * @module model/AuthResponse
 * @version 1.0.0
 */
class AuthResponse {
    /**
     * Constructs a new <code>AuthResponse</code>.
     * @alias module:model/AuthResponse
     * @param accessToken {String} 
     * @param tokenType {String} 
     * @param expiresIn {Number} 
     * @param user {module:model/UserBasicInfo} 
     */
    constructor(accessToken, tokenType, expiresIn, user) { 
        
        AuthResponse.initialize(this, accessToken, tokenType, expiresIn, user);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accessToken, tokenType, expiresIn, user) { 
        obj['accessToken'] = accessToken;
        obj['tokenType'] = tokenType;
        obj['expiresIn'] = expiresIn;
        obj['user'] = user;
    }

    /**
     * Constructs a <code>AuthResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthResponse} obj Optional instance to populate.
     * @return {module:model/AuthResponse} The populated <code>AuthResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthResponse();

            if (data.hasOwnProperty('accessToken')) {
                obj['accessToken'] = ApiClient.convertToType(data['accessToken'], 'String');
            }
            if (data.hasOwnProperty('tokenType')) {
                obj['tokenType'] = ApiClient.convertToType(data['tokenType'], 'String');
            }
            if (data.hasOwnProperty('expiresIn')) {
                obj['expiresIn'] = ApiClient.convertToType(data['expiresIn'], 'Number');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = UserBasicInfo.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['accessToken'] && !(typeof data['accessToken'] === 'string' || data['accessToken'] instanceof String)) {
            throw new Error("Expected the field `accessToken` to be a primitive type in the JSON string but got " + data['accessToken']);
        }
        // ensure the json data is a string
        if (data['tokenType'] && !(typeof data['tokenType'] === 'string' || data['tokenType'] instanceof String)) {
            throw new Error("Expected the field `tokenType` to be a primitive type in the JSON string but got " + data['tokenType']);
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          UserBasicInfo.validateJSON(data['user']);
        }

        return true;
    }


}

AuthResponse.RequiredProperties = ["accessToken", "tokenType", "expiresIn", "user"];

/**
 * @member {String} accessToken
 */
AuthResponse.prototype['accessToken'] = undefined;

/**
 * @member {String} tokenType
 */
AuthResponse.prototype['tokenType'] = undefined;

/**
 * @member {Number} expiresIn
 */
AuthResponse.prototype['expiresIn'] = undefined;

/**
 * @member {module:model/UserBasicInfo} user
 */
AuthResponse.prototype['user'] = undefined;






export default AuthResponse;

