/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ForgotPassword200Response model module.
 * @module model/ForgotPassword200Response
 * @version 1.0.0
 */
class ForgotPassword200Response {
    /**
     * Constructs a new <code>ForgotPassword200Response</code>.
     * @alias module:model/ForgotPassword200Response
     * @param success {Boolean} 
     * @param data {Object} The response data
     */
    constructor(success, data) { 
        
        ForgotPassword200Response.initialize(this, success, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, data) { 
        obj['success'] = success;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>ForgotPassword200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ForgotPassword200Response} obj Optional instance to populate.
     * @return {module:model/ForgotPassword200Response} The populated <code>ForgotPassword200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForgotPassword200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ForgotPassword200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ForgotPassword200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ForgotPassword200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ForgotPassword200Response.RequiredProperties = ["success", "data"];

/**
 * @member {Boolean} success
 */
ForgotPassword200Response.prototype['success'] = undefined;

/**
 * The response data
 * @member {Object} data
 */
ForgotPassword200Response.prototype['data'] = undefined;






export default ForgotPassword200Response;

