/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlanResponse from './PlanResponse';

/**
 * The GetAllPlans200Response model module.
 * @module model/GetAllPlans200Response
 * @version 1.0.0
 */
class GetAllPlans200Response {
    /**
     * Constructs a new <code>GetAllPlans200Response</code>.
     * @alias module:model/GetAllPlans200Response
     */
    constructor() { 
        
        GetAllPlans200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAllPlans200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAllPlans200Response} obj Optional instance to populate.
     * @return {module:model/GetAllPlans200Response} The populated <code>GetAllPlans200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAllPlans200Response();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [PlanResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetAllPlans200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetAllPlans200Response</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                PlanResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} total
 */
GetAllPlans200Response.prototype['total'] = undefined;

/**
 * @member {Array.<module:model/PlanResponse>} items
 */
GetAllPlans200Response.prototype['items'] = undefined;






export default GetAllPlans200Response;

