/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlanCreateRequest model module.
 * @module model/PlanCreateRequest
 * @version 1.0.0
 */
class PlanCreateRequest {
    /**
     * Constructs a new <code>PlanCreateRequest</code>.
     * @alias module:model/PlanCreateRequest
     * @param title {String} 
     * @param quantity {Number} 
     * @param jobDescription {String} 
     * @param requiredCPA {Number} 
     */
    constructor(title, quantity, jobDescription, requiredCPA) { 
        
        PlanCreateRequest.initialize(this, title, quantity, jobDescription, requiredCPA);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, quantity, jobDescription, requiredCPA) { 
        obj['title'] = title;
        obj['quantity'] = quantity;
        obj['jobDescription'] = jobDescription;
        obj['requiredCPA'] = requiredCPA;
    }

    /**
     * Constructs a <code>PlanCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlanCreateRequest} obj Optional instance to populate.
     * @return {module:model/PlanCreateRequest} The populated <code>PlanCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlanCreateRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('jobDescription')) {
                obj['jobDescription'] = ApiClient.convertToType(data['jobDescription'], 'String');
            }
            if (data.hasOwnProperty('requiredCPA')) {
                obj['requiredCPA'] = ApiClient.convertToType(data['requiredCPA'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PlanCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PlanCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PlanCreateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['jobDescription'] && !(typeof data['jobDescription'] === 'string' || data['jobDescription'] instanceof String)) {
            throw new Error("Expected the field `jobDescription` to be a primitive type in the JSON string but got " + data['jobDescription']);
        }

        return true;
    }


}

PlanCreateRequest.RequiredProperties = ["title", "quantity", "jobDescription", "requiredCPA"];

/**
 * @member {String} title
 */
PlanCreateRequest.prototype['title'] = undefined;

/**
 * @member {Number} quantity
 */
PlanCreateRequest.prototype['quantity'] = undefined;

/**
 * @member {String} jobDescription
 */
PlanCreateRequest.prototype['jobDescription'] = undefined;

/**
 * @member {Number} requiredCPA
 */
PlanCreateRequest.prototype['requiredCPA'] = undefined;






export default PlanCreateRequest;

