/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserSelfUpdateRequest model module.
 * @module model/UserSelfUpdateRequest
 * @version 1.0.0
 */
class UserSelfUpdateRequest {
    /**
     * Constructs a new <code>UserSelfUpdateRequest</code>.
     * @alias module:model/UserSelfUpdateRequest
     * @param username {String} 
     * @param email {String} 
     * @param phone {String} 
     * @param address {String} 
     */
    constructor(username, email, phone, address) { 
        
        UserSelfUpdateRequest.initialize(this, username, email, phone, address);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, email, phone, address) { 
        obj['username'] = username;
        obj['email'] = email;
        obj['phone'] = phone;
        obj['address'] = address;
    }

    /**
     * Constructs a <code>UserSelfUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserSelfUpdateRequest} obj Optional instance to populate.
     * @return {module:model/UserSelfUpdateRequest} The populated <code>UserSelfUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserSelfUpdateRequest();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserSelfUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserSelfUpdateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserSelfUpdateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }

        return true;
    }


}

UserSelfUpdateRequest.RequiredProperties = ["username", "email", "phone", "address"];

/**
 * @member {String} username
 */
UserSelfUpdateRequest.prototype['username'] = undefined;

/**
 * @member {String} email
 */
UserSelfUpdateRequest.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
UserSelfUpdateRequest.prototype['phone'] = undefined;

/**
 * @member {String} address
 */
UserSelfUpdateRequest.prototype['address'] = undefined;






export default UserSelfUpdateRequest;

