/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     * @param id {String} 
     * @param username {String} 
     * @param email {String} 
     * @param phone {String} 
     * @param fullName {String} 
     * @param role {module:model/User.RoleEnum} 
     * @param status {module:model/User.StatusEnum} 
     * @param isVerified {Boolean} Indicates if the user's email is verified
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     * @param dateOfBirth {Date} 
     * @param address {String} 
     * @param sex {module:model/User.SexEnum} 
     * @param school {String} 
     * @param department {String} 
     * @param position {String} 
     * @param CPA {Number} 
     * @param password {String} 
     */
    constructor(id, username, email, phone, fullName, role, status, isVerified, createdAt, updatedAt, dateOfBirth, address, sex, school, department, position, CPA, password) { 
        
        User.initialize(this, id, username, email, phone, fullName, role, status, isVerified, createdAt, updatedAt, dateOfBirth, address, sex, school, department, position, CPA, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, username, email, phone, fullName, role, status, isVerified, createdAt, updatedAt, dateOfBirth, address, sex, school, department, position, CPA, password) { 
        obj['id'] = id;
        obj['username'] = username;
        obj['email'] = email;
        obj['phone'] = phone;
        obj['fullName'] = fullName;
        obj['role'] = role;
        obj['status'] = status;
        obj['isVerified'] = isVerified;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
        obj['dateOfBirth'] = dateOfBirth;
        obj['address'] = address;
        obj['sex'] = sex;
        obj['school'] = school;
        obj['department'] = department;
        obj['position'] = position;
        obj['CPA'] = CPA;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('fullName')) {
                obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('isVerified')) {
                obj['isVerified'] = ApiClient.convertToType(data['isVerified'], 'Boolean');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'Date');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('sex')) {
                obj['sex'] = ApiClient.convertToType(data['sex'], 'String');
            }
            if (data.hasOwnProperty('school')) {
                obj['school'] = ApiClient.convertToType(data['school'], 'String');
            }
            if (data.hasOwnProperty('department')) {
                obj['department'] = ApiClient.convertToType(data['department'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'String');
            }
            if (data.hasOwnProperty('CPA')) {
                obj['CPA'] = ApiClient.convertToType(data['CPA'], 'Number');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>User</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>User</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of User.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['fullName'] && !(typeof data['fullName'] === 'string' || data['fullName'] instanceof String)) {
            throw new Error("Expected the field `fullName` to be a primitive type in the JSON string but got " + data['fullName']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['sex'] && !(typeof data['sex'] === 'string' || data['sex'] instanceof String)) {
            throw new Error("Expected the field `sex` to be a primitive type in the JSON string but got " + data['sex']);
        }
        // ensure the json data is a string
        if (data['school'] && !(typeof data['school'] === 'string' || data['school'] instanceof String)) {
            throw new Error("Expected the field `school` to be a primitive type in the JSON string but got " + data['school']);
        }
        // ensure the json data is a string
        if (data['department'] && !(typeof data['department'] === 'string' || data['department'] instanceof String)) {
            throw new Error("Expected the field `department` to be a primitive type in the JSON string but got " + data['department']);
        }
        // ensure the json data is a string
        if (data['position'] && !(typeof data['position'] === 'string' || data['position'] instanceof String)) {
            throw new Error("Expected the field `position` to be a primitive type in the JSON string but got " + data['position']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }


}

User.RequiredProperties = ["id", "username", "email", "phone", "fullName", "role", "status", "isVerified", "createdAt", "updatedAt", "dateOfBirth", "address", "sex", "school", "department", "position", "CPA", "password"];

/**
 * @member {String} id
 */
User.prototype['id'] = undefined;

/**
 * @member {String} username
 */
User.prototype['username'] = undefined;

/**
 * @member {String} email
 */
User.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
User.prototype['phone'] = undefined;

/**
 * @member {String} fullName
 */
User.prototype['fullName'] = undefined;

/**
 * @member {module:model/User.RoleEnum} role
 */
User.prototype['role'] = undefined;

/**
 * @member {module:model/User.StatusEnum} status
 */
User.prototype['status'] = undefined;

/**
 * Indicates if the user's email is verified
 * @member {Boolean} isVerified
 */
User.prototype['isVerified'] = undefined;

/**
 * @member {Date} createdAt
 */
User.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
User.prototype['updatedAt'] = undefined;

/**
 * @member {Date} dateOfBirth
 */
User.prototype['dateOfBirth'] = undefined;

/**
 * @member {String} address
 */
User.prototype['address'] = undefined;

/**
 * @member {module:model/User.SexEnum} sex
 */
User.prototype['sex'] = undefined;

/**
 * @member {String} school
 */
User.prototype['school'] = undefined;

/**
 * @member {String} department
 */
User.prototype['department'] = undefined;

/**
 * @member {String} position
 */
User.prototype['position'] = undefined;

/**
 * @member {Number} CPA
 */
User.prototype['CPA'] = undefined;

/**
 * @member {String} password
 */
User.prototype['password'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
User['RoleEnum'] = {

    /**
     * value: "ADMIN"
     * @const
     */
    "ADMIN": "ADMIN",

    /**
     * value: "PERSONNEL MANAGER"
     * @const
     */
    "PERSONNEL MANAGER": "PERSONNEL MANAGER",

    /**
     * value: "RECTOR"
     * @const
     */
    "RECTOR": "RECTOR",

    /**
     * value: "UNIT MANAGER"
     * @const
     */
    "UNIT MANAGER": "UNIT MANAGER"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
User['StatusEnum'] = {

    /**
     * value: "ACTIVE"
     * @const
     */
    "ACTIVE": "ACTIVE",

    /**
     * value: "INACTIVE"
     * @const
     */
    "INACTIVE": "INACTIVE",

    /**
     * value: "PENDING"
     * @const
     */
    "PENDING": "PENDING"
};


/**
 * Allowed values for the <code>sex</code> property.
 * @enum {String}
 * @readonly
 */
User['SexEnum'] = {

    /**
     * value: "MALE"
     * @const
     */
    "MALE": "MALE",

    /**
     * value: "FEMALE"
     * @const
     */
    "FEMALE": "FEMALE"
};



export default User;

