/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserCreateRequest model module.
 * @module model/UserCreateRequest
 * @version 1.0.0
 */
class UserCreateRequest {
    /**
     * Constructs a new <code>UserCreateRequest</code>.
     * @alias module:model/UserCreateRequest
     * @param username {String} 
     * @param email {String} 
     * @param phone {String} 
     * @param fullName {String} 
     * @param role {module:model/UserCreateRequest.RoleEnum} 
     * @param position {String} 
     * @param department {String} 
     * @param dateOfBirth {Date} 
     * @param address {String} 
     * @param password {String} 
     */
    constructor(username, email, phone, fullName, role, position, department, dateOfBirth, address, password) { 
        
        UserCreateRequest.initialize(this, username, email, phone, fullName, role, position, department, dateOfBirth, address, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, email, phone, fullName, role, position, department, dateOfBirth, address, password) { 
        obj['username'] = username;
        obj['email'] = email;
        obj['phone'] = phone;
        obj['fullName'] = fullName;
        obj['role'] = role;
        obj['position'] = position;
        obj['department'] = department;
        obj['dateOfBirth'] = dateOfBirth;
        obj['address'] = address;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>UserCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserCreateRequest} obj Optional instance to populate.
     * @return {module:model/UserCreateRequest} The populated <code>UserCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserCreateRequest();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('fullName')) {
                obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'String');
            }
            if (data.hasOwnProperty('department')) {
                obj['department'] = ApiClient.convertToType(data['department'], 'String');
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'Date');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserCreateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['fullName'] && !(typeof data['fullName'] === 'string' || data['fullName'] instanceof String)) {
            throw new Error("Expected the field `fullName` to be a primitive type in the JSON string but got " + data['fullName']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['position'] && !(typeof data['position'] === 'string' || data['position'] instanceof String)) {
            throw new Error("Expected the field `position` to be a primitive type in the JSON string but got " + data['position']);
        }
        // ensure the json data is a string
        if (data['department'] && !(typeof data['department'] === 'string' || data['department'] instanceof String)) {
            throw new Error("Expected the field `department` to be a primitive type in the JSON string but got " + data['department']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }


}

UserCreateRequest.RequiredProperties = ["username", "email", "phone", "fullName", "role", "position", "department", "dateOfBirth", "address", "password"];

/**
 * @member {String} username
 */
UserCreateRequest.prototype['username'] = undefined;

/**
 * @member {String} email
 */
UserCreateRequest.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
UserCreateRequest.prototype['phone'] = undefined;

/**
 * @member {String} fullName
 */
UserCreateRequest.prototype['fullName'] = undefined;

/**
 * @member {module:model/UserCreateRequest.RoleEnum} role
 */
UserCreateRequest.prototype['role'] = undefined;

/**
 * @member {String} position
 */
UserCreateRequest.prototype['position'] = undefined;

/**
 * @member {String} department
 */
UserCreateRequest.prototype['department'] = undefined;

/**
 * @member {Date} dateOfBirth
 */
UserCreateRequest.prototype['dateOfBirth'] = undefined;

/**
 * @member {String} address
 */
UserCreateRequest.prototype['address'] = undefined;

/**
 * @member {String} password
 */
UserCreateRequest.prototype['password'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
UserCreateRequest['RoleEnum'] = {

    /**
     * value: "ADMIN"
     * @const
     */
    "ADMIN": "ADMIN",

    /**
     * value: "PERSONNEL MANAGER"
     * @const
     */
    "PERSONNEL MANAGER": "PERSONNEL MANAGER",

    /**
     * value: "RECTOR"
     * @const
     */
    "RECTOR": "RECTOR",

    /**
     * value: "UNIT MANAGER"
     * @const
     */
    "UNIT MANAGER": "UNIT MANAGER"
};



export default UserCreateRequest;

