/**
 * Recruitment Management System API
 * API for managing recruitment processes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thanhthuongnlp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserAdminUpdateRequest model module.
 * @module model/UserAdminUpdateRequest
 * @version 1.0.0
 */
class UserAdminUpdateRequest {
    /**
     * Constructs a new <code>UserAdminUpdateRequest</code>.
     * @alias module:model/UserAdminUpdateRequest
     * @param role {module:model/UserAdminUpdateRequest.RoleEnum} 
     * @param position {String} 
     * @param department {String} 
     */
    constructor(role, position, department) { 
        
        UserAdminUpdateRequest.initialize(this, role, position, department);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, role, position, department) { 
        obj['role'] = role;
        obj['position'] = position;
        obj['department'] = department;
    }

    /**
     * Constructs a <code>UserAdminUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserAdminUpdateRequest} obj Optional instance to populate.
     * @return {module:model/UserAdminUpdateRequest} The populated <code>UserAdminUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserAdminUpdateRequest();

            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'String');
            }
            if (data.hasOwnProperty('department')) {
                obj['department'] = ApiClient.convertToType(data['department'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserAdminUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserAdminUpdateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserAdminUpdateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['position'] && !(typeof data['position'] === 'string' || data['position'] instanceof String)) {
            throw new Error("Expected the field `position` to be a primitive type in the JSON string but got " + data['position']);
        }
        // ensure the json data is a string
        if (data['department'] && !(typeof data['department'] === 'string' || data['department'] instanceof String)) {
            throw new Error("Expected the field `department` to be a primitive type in the JSON string but got " + data['department']);
        }

        return true;
    }


}

UserAdminUpdateRequest.RequiredProperties = ["role", "position", "department"];

/**
 * @member {module:model/UserAdminUpdateRequest.RoleEnum} role
 */
UserAdminUpdateRequest.prototype['role'] = undefined;

/**
 * @member {String} position
 */
UserAdminUpdateRequest.prototype['position'] = undefined;

/**
 * @member {String} department
 */
UserAdminUpdateRequest.prototype['department'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
UserAdminUpdateRequest['RoleEnum'] = {

    /**
     * value: "ADMIN"
     * @const
     */
    "ADMIN": "ADMIN",

    /**
     * value: "PERSONNEL MANAGER"
     * @const
     */
    "PERSONNEL MANAGER": "PERSONNEL MANAGER",

    /**
     * value: "RECTOR"
     * @const
     */
    "RECTOR": "RECTOR",

    /**
     * value: "UNIT MANAGER"
     * @const
     */
    "UNIT MANAGER": "UNIT MANAGER"
};



export default UserAdminUpdateRequest;

